"""
Checks for the BCA export interface (spec 06 §3, work item B4). The schema and
round-trip checks read the generated gz, so run the exports first:
    python bca_export.py harbor
    python bca_export.py streetcar
    python test_bca_export.py

  - test_abc_weights_normalize: the refactored abc_weights returns per-kernel
    weights that sum to 1, one array per label (all five launch/matured
    kernels), tighter sigma concentrating more mass near mu (fast; no file).
  - test_schema_shape(name): every §3 key is present with the right array
    lengths (N) and float dtype; abc_weights present iff a calibration target
    exists (harbor yes -> all five kernel labels from reweight_abc, streetcar
    no -> absence reason instead).
  - test_round_trip(name): reuses bca_export.roundtrip_check -- harbor's
    weighted ABC central-kernel retain P50 vs abc_harbor.json["kernels"][central],
    streetcar's unweighted retain P50 vs results_streetcar.json, to 4 sig figs.

usage: python test_bca_export.py [harbor streetcar]
"""
import gzip, hashlib, json, os, sys
import numpy as np
from model import N, PRIORS
from reweight_abc import abc_weights, get_kernels, central_label
import bca_export as bx

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

SCALAR_KEYS = ("newline", "total", "um_infra", "um_margin", "um0_infra",
               "um0_margin", "um_roh_infra", "um_roh_margin", "fare_burden",
               "fare_receipts_infra", "fare_receipts_margin", "cm_visitor")
SEG_KEYS = ("cm_seg", "cm_seg_fullod")
N_PRIORS = 19   # update when appending priors (append-last discipline, see model.py PRIORS)

# Committed ORDER FINGERPRINT: sha256 of the ordered prior-name tuple (spec 08
# §2/§4). Updating this hash is the explicit act of appending a prior -- never
# reorder. A reorder shifts draw_params' rng stream and silently changes every
# result; a consistent renumber passes any static check, so the guard is a
# fingerprint against a reference that does not derive from the registry.
PRIOR_ORDER_FINGERPRINT = \
    "f0bb42f69644483fddfbb18cb97c24b99c70d8bbd2fc9792695cfda659c4235d"


def _load(name):
    p = os.path.join(bx.OUT, f"bca_export_{name}.json.gz")
    with gzip.open(p, "rt", encoding="utf-8") as f:
        return json.load(f)


def test_prior_order_fingerprint():
    """The reorder guard: the ordered prior-name tuple must hash to the pinned
    value, and PRIORS must be GENERATED by assumptions.build_priors() (not a
    hand-typed literal). See PRIOR_ORDER_FINGERPRINT above."""
    names = tuple(PRIORS.keys())
    assert len(names) == N_PRIORS, (len(names), N_PRIORS)
    fp = hashlib.sha256("|".join(names).encode("utf-8")).hexdigest()
    assert fp == PRIOR_ORDER_FINGERPRINT, (
        f"prior order changed -> {fp}\n  names = {names}\n"
        "  If you APPENDED a prior (append-last discipline), bump N_PRIORS and "
        "update PRIOR_ORDER_FINGERPRINT -- that is the explicit act. NEVER "
        "reorder existing priors: it shifts the rng stream and silently changes "
        "every result.")
    assert getattr(PRIORS, "generated_by", None) == "assumptions.build_priors", \
        "model.PRIORS is not the build_priors() sentinel dict"
    print(f"  test_prior_order_fingerprint OK  ({N_PRIORS} priors, "
          f"fp {fp[:12]}...)")


def test_abc_weights_normalize():
    pred = np.linspace(3000.0, 8000.0, 1000)
    kernels = get_kernels()                       # single source of truth
    w = abc_weights(pred, kernels)
    labels = {lbl for lbl, _, _ in kernels}
    assert set(w) == labels, set(w)
    assert len(w) == 5, len(w)                     # two launch, launch14, matured
    for lbl, v in w.items():
        assert v.shape == (1000,), (lbl, v.shape)
        assert abs(v.sum() - 1.0) < 1e-12, (lbl, v.sum())
    # the two launch kernels share MU_LAUNCH (~5,938); the s350 is tighter
    mu_launch = {lbl: mu for lbl, mu, _ in kernels}["543_launch_s500"]
    near = np.abs(pred - mu_launch) < 200.0
    assert (w["543_launch_s350"][near].sum()
            > w["543_launch_s500"][near].sum()), "tighter sigma not tighter"
    print("  test_abc_weights_normalize OK")


def test_schema_shape(name):
    e = _load(name)
    for k in ("corridor", "design", "n", "seed", "eq_days", "scenarios",
              "params", "base_service", "routes_removed"):
        assert k in e, f"missing top-level key {k}"
    assert e["corridor"] == name, e["corridor"]
    assert e["n"] == N and e["eq_days"] == [300, 330]
    for scen in ("fold", "retain"):
        s = e["scenarios"][scen]
        for k in SCALAR_KEYS:
            assert len(s[k]) == N, f"{scen}.{k} len {len(s[k])} != {N}"
            assert isinstance(s[k][0], float), f"{scen}.{k} not float"
        for k in SEG_KEYS:
            assert len(s[k]) == 3, f"{scen}.{k} not 3 segments"
            assert all(len(seg) == N for seg in s[k]), f"{scen}.{k} bad seg len"
    assert len(e["params"]) == N_PRIORS + 1, len(e["params"])   # 19 + anchor
    assert len(e["params"]["anchor"]) == N
    if name == "harbor":
        assert set(e["abc_weights"]) == {lbl for lbl, _, _ in get_kernels()}
        assert len(e["abc_weights"]) == 5, len(e["abc_weights"])
        assert all(len(v) == N for v in e["abc_weights"].values())
        assert "abc_weights_absent_reason" not in e
        # routes_removed is top-level; base_service is ONLY rev_hours_weekday
        assert e["routes_removed"]["fold"] == ["43", "543"], e["routes_removed"]
        assert e["routes_removed"]["retain"] == ["543"], e["routes_removed"]
        assert set(e["base_service"]) == {"rev_hours_weekday"}, e["base_service"]
        assert e["base_service"]["rev_hours_weekday"]["543"] > 0
    else:
        assert "abc_weights" not in e, "streetcar should have no abc_weights"
        assert e["abc_weights_absent_reason"], "missing absence reason"
        # streetcar folds nothing: routes_removed empty, base_service {} (no
        # rev_hours_weekday when routes_removed is empty)
        assert e["routes_removed"]["fold"] == [] and e["routes_removed"]["retain"] == []
        assert e["base_service"] == {}, e["base_service"]
    print(f"  test_schema_shape({name}) OK  "
          f"({len(SCALAR_KEYS) + len(SEG_KEYS)} streams x 2 scenarios, "
          f"{len(e['params'])} param arrays)")


def test_round_trip(name):
    p = os.path.join(bx.OUT, f"bca_export_{name}.json.gz")
    assert bx.roundtrip_check(name, p), f"round-trip failed for {name}"
    print(f"  test_round_trip({name}) OK")


if __name__ == "__main__":
    names = sys.argv[1:] or ["harbor", "streetcar"]
    test_prior_order_fingerprint()
    test_abc_weights_normalize()
    for nm in names:
        test_schema_shape(nm)
        test_round_trip(nm)
    print("ALL CHECKS PASS")
